version: 0.2

phases:
  install:
    commands:
      - echo Install Node JS
      - curl -fsSL https://deb.nodesource.com/setup_12.x | bash -
      - apt install -y nodejs
  pre_build:
    commands:
      - echo Install dependencies
      - npm install
  build:
    commands:
      - echo Run build
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build